REM Author : Christopher Panayi
REM Version : 1.0
REM Description: Call certutil with quoted path and provide hashes as output. Parse out spaces and extraneous output generated by certutil.

@ECHO off
setlocal DisableDelayedExpansion
cls

echo SHGW 
echo Generating hash for %1
echo.

if "%2"=="MD5" set HASH_LIST=(MD5)
if "%2"=="SHA1" set HASH_LIST=(SHA1)
if "%2"=="SHA256" set HASH_LIST=(SHA256)
if "%2"=="SHA384" set HASH_LIST=(SHA384)
if "%2"=="SHA512" set HASH_LIST=(SHA512)
if "%HASH_LIST%"=="" set HASH_LIST=(MD5 SHA1 SHA256 SHA384 SHA512)

for %%j in %HASH_LIST% do (
setlocal DisableDelayedExpansion
set /a count=0

FOR /F "delims=" %%i IN ('certutil -hashfile %1 %%j') DO (
setlocal EnableDelayedExpansion

 if !count!==1 (
	set out=%%i
 ) 
 set /a count+=1
)

set out=!out: =!
ECHO %%j: !out!
)

echo.
PAUSE